### ISSUE TITLE
remove `letrec` from early languages

### ISSUE THREAD

**Issue by shriram** [shriram/smol#1]
It doesn't really make sense to have `letrec` in the pre-`lambda` languages. Remove them.

**Comment by LuKC1024** [comment]
Oops, we forgot to remove `letrec` from doc.

**Comment by LuKC1024** [comment]
While checking the document, I realize `letrec` should not be provided in `dyn-scope-is-bad`.

> For now @code{let*} and @code{letrec} aren't
present. The former is out of implementor laziness, but it's a useful
puzzle to ponder is why @code{letrec} hasn't been provided.
