### ISSUE TITLE
Change smol/dyn-scope-is-bad to match Shriram's 2021 textbook

### ISSUE THREAD

**Issue by LuKC1024** [shriram/smol#12]
That is, the only place where the interpreter goes crazy is to fetch environment from the calling side rather than from the place where the closure is constructed.

**Comment by LuKC1024** [comment]
A test program
```
#lang smol/dyn-scope-is-bad
(deffun (fibber x)
  (if (< x 2)
      (if (<= x 0) 0 1)
      (+ (fibber (- x 1)) (fibber (- x 2)))))

(fibber 5)
```

**Comment by shriram** [comment]
Write these as tests, not just as "programs".

**Comment by LuKC1024** [comment]
Fixed.
